### ISSUE TITLE
Using index.svelte to showcase this package instead of using another app?

### ISSUE THREAD

**Issue by amr3k** [shinokada/svelte-utterances#8]
Maybe the [web app](https://svelte-utterances.vercel.app/) should exist in this package to add a demo of all features upon they are implemented.

This should make it easier to review new features, enhancement in each pull request.

**Comment by shinokada** [comment]
Thank you for your suggestion.
There are two branches, main and demo-site.
The reason I separated to two branches is that demo-site has many devDependencies which are not used in the main.
I use the main to create a NPM package, and use the demo-site for the [web site](https://svelte-utterances.vercel.app/).

**Comment by amr3k** [comment]
Ok this was a good idea

**Comment by shinokada** [comment]
I will add this in README how to check out to demo-site to see it in action.
Thanks.
